### ISSUE TITLE
Austria Store wont start

### ISSUE THREAD

**Issue by McFly24** [timbru31/mms-stockshock#486]
i think there is a bug when i'm starting for the Austria store
email and password are correct

```
simon@dockeragent:~/npm/mms-stockshock$ npm start -- --store mmat

> stockshock@5.12.1 prestart
> npm run build


> stockshock@5.12.1 build
> tsc


> stockshock@5.12.1 start
> node dist/src/index.js "--store" "mmat"

2022-01-03 23:44:26 [🧚] info: 💤 Delaying start until Discord bot is ready
2022-01-03 23:44:26 [🧚] info: 💤 Delaying start until Discord bot is ready
2022-01-03 23:44:26 [🧚] info: 👌 Discord bot integration ready
2022-01-03 23:44:28 [🧚] info: 🤖 Beep, I'm alive and well checking your stock
2022-01-03 23:44:28 [🧚] info: 💌 Checking wishlist items for account MAIL
2022-01-03 23:44:28 [🧚] info: Re-Login required!
2022-01-03 23:44:32 [🧚] info: Fresh context created!
2022-01-03 23:44:32 [⚡️] error: Login query did not succeed, status code: 200
2022-01-03 23:44:32 [⚡️] error: Error: [
  {
    message: 'PersistedQueryNotFound',
    extensions: {
      code: 'PERSISTED_QUERY_NOT_FOUND',
      flowId: 'a6699ebc-b8c4-40bc-8fb2-adf167a2fd1e'
    }
  }
]
2022-01-03 23:44:32 [🧚] info: 😵 Login did not succeed. Status 200
2022-01-03 23:44:33 [🧚] info: ⚡️ Boop, I'm alive but checking wishlist for MAIL errored, Error: Login did not succeed. Status 200
    at BrowserManager.logIn (/home/simon/npm/mms-stockshock/dist/src/core/browser-manager.js:131:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async reLoginIfRequired (/home/simon/npm/mms-stockshock/dist/src/index.js:32:9)
    at async /home/simon/npm/mms-stockshock/dist/src/index.js:142:21
```

**Comment by timbru31** [comment]
See note in the README:
>  You need to supply the query hashes from the MM/S API as they change too often to maintain!
